// I'm not sure what does what and the documentation is crap

export const filters = [
  {value: "eq_any",             label: "equals any"},
  {value: "eq_all",             label: "equals all"},
  {value: "not_eq_any",         label: "is not equal to any"},
  {value: "not_eq_all",         label: "is not equal to all"},
  {value: "matches_any",        label: "matches any"},
  {value: "matches_all",        label: "matches all"},
  {value: "does_not_match_any", label: "doesn't match any"},
  {value: "does_not_match_all", label: "doesn't match all"},
  {value: "lt_any",             label: "is less than any"},
  {value: "lt_all",             label: "is less than all"},
  {value: "lteq_any",           label: "is less than or equal to any"},
  {value: "lteq_all",           label: "is less than or equal to all"},
  {value: "gt_any",             label: "is greater than any"},
  {value: "gt_all",             label: "is greater than all"},
  {value: "gteq_any",           label: "is greater than or equal to any"},
  {value: "gteq_all",           label: "is greater than or equal to all"},
  {value: "in_any",             label: "in any"},
  {value: "in_all",             label: "in all"},
  {value: "not_in_any",         label: "not in any"},
  {value: "not_in_all",         label: "not in all"},
  {value: "cont_any",           label: "contains any"},
  {value: "cont_all",           label: "contains all"},
  {value: "not_cont_any",       label: "doesn't contain any"},
  {value: "not_cont_all",       label: "doesn't contain all"},
  {value: "start_any",          label: "starts with any"},
  {value: "start_all",          label: "starts with all"},
  {value: "not_start_any",      label: "doesn't start with any"},
  {value: "not_start_all",      label: "doesn't start with all"},
  {value: "end_any",            label: "ends with any"},
  {value: "end_all",            label: "ends with all"},
  {value: "not_end_any",        label: "doesn't end with any"},
  {value: "not_end_all",        label: "doesn't end with all"},
  {value: "true",               label: "is true"},
  {value: "false",              label: "is false"},
  {value: "present",            label: "is present"},
  {value: "null",               label: "is null"},
  {value: "not_null",           label: "is not null"}
]